# Generated by Django 4.2.7 on 2023-11-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=250)),
                ('movied', models.CharField(max_length=100000)),
                ('moviei', models.CharField(max_length=350)),
                ('moviet', models.CharField(max_length=250)),
                ('dl1', models.CharField(max_length=250)),
                ('dl2', models.CharField(max_length=250)),
            ],
        ),
    ]
